name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore:
      - '.github/workflows/release.yml'

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml
